calendar:
  id: hlclne2tbhr27ijqbkadigkjqk@group.calendar.google.com

discord:
  commands:
    prefix: '!'
    caseInsensitive: true
    timeout: '5s'
  permissions:
    preload: '248612704019808258:admin'
