spring:
  datasource:
    url: 'jdbc:sqlite:/home/pi/fracktail/sql/fracktail.db'
    initialization-mode: always

logging:
  level:
    com.github.lucbui: INFO

calendar:
  tokenPath: /home/pi/tokens

discord:
  presence:
    type: DO_NOT_DISTURB
    playing: ''

