logging:
  level:
    com.github.lucbui: DEBUG

calendar:
  id: hlclne2tbhr27ijqbkadigkjqk@group.calendar.google.com
  tokenPath: tokens

discord:
  commands:
    prefix: '!'
    caseInsensitive: true
    timeout: '5s'
