spring:
  profiles:
    active: local

logging:
  level:
    com.github.lucbui: DEBUG

calendar:
  id: hlclne2tbhr27ijqbkadigkjqk@group.calendar.google.com

discord:
  timeout:
    enabled: true
  permissions:
    enabled: true
  commands:
    prefix: '!'
    caseInsensitive: true