spring:
  profiles:
    active: local

logging:
  level:
    com.github.lucbui: DEBUG

calendar:
  id: hlclne2tbhr27ijqbkadigkjqk@group.calendar.google.com

discord:
  commands:
    prefix: '!'
    caseInsensitive: true
    timeout: '5s'