logging:
  level:
    com.github.lucbui.magic: DEBUG

calendar:
  id: hlclne2tbhr27ijqbkadigkjqk@group.calendar.google.com

discord:
  commands:
    prefix: '!'
    caseInsensitive: true
    timeout: '5s'

scheduler:
  enabled: true
