logging:
  level:
    com.github.lucbui: DEBUG

calendar:
  id: hlclne2tbhr27ijqbkadigkjqk@group.calendar.google.com
  tokenPath: tokens

discord:
  presence:
    type: DO_NOT_DISTURB
    playing: 'in Debug Mode!'
  commands:
    prefix: '!'
    caseInsensitive: true
    timeout: '5s'

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: 'jdbc:sqlite::memory:'
